// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhrUVuokqSyOqnV274CS2ZWKELId92qo',
    appId: '1:608110947148:web:526f13ef8cb5b0f117fde9',
    messagingSenderId: '608110947148',
    projectId: 'tiffin-time-819e1',
    authDomain: 'tiffin-time-819e1.firebaseapp.com',
    storageBucket: 'tiffin-time-819e1.appspot.com',
    measurementId: 'G-GLCH8YQ3NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9OMoY05VrSB2EpnQUwpQCOWAOnf1_I4',
    appId: '1:608110947148:android:97a16fba8deb8e6717fde9',
    messagingSenderId: '608110947148',
    projectId: 'tiffin-time-819e1',
    storageBucket: 'tiffin-time-819e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD54PzbKyNHG4jbGPSHmxYWhNCloUXm_mM',
    appId: '1:608110947148:ios:f69e9e8852ad916a17fde9',
    messagingSenderId: '608110947148',
    projectId: 'tiffin-time-819e1',
    storageBucket: 'tiffin-time-819e1.appspot.com',
    iosBundleId: 'com.example.advBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD54PzbKyNHG4jbGPSHmxYWhNCloUXm_mM',
    appId: '1:608110947148:ios:f69e9e8852ad916a17fde9',
    messagingSenderId: '608110947148',
    projectId: 'tiffin-time-819e1',
    storageBucket: 'tiffin-time-819e1.appspot.com',
    iosBundleId: 'com.example.advBasics',
  );
}
